export const colours = [
	'alice blue',
	'antique white',
	'aqua',
	'aquamarine',
	'azure',
	'beige',
	'bisque',
	'black',
	'blanched almond',
	'blue',
	'blue violet',
	'brown',
	'buff',
	'burlywood',
	'cadet blue',
	'chartreuse',
	'chocolate',
	'coral',
	'cornflower blue',
	'cornsilk',
	'crimson',
	'cyan',
	'dark blue',
	'dark brown',
	'dark buff',
	'dark cyan',
	'dark gold',
	'dark goldenrod',
	'dark gray',
	'dark green',
	'dark ivory',
	'dark khaki',
	'dark magenta',
	'dark mustard',
	'dark olive green',
	'dark orange',
	'dark orchid',
	'dark pink',
	'dark red',
	'dark salmon',
	'dark sea green',
	'dark silver',
	'dark slate blue',
	'dark slate gray',
	'dark turquoise',
	'dark violet',
	'dark yellow',
	'deep pink',
	'deep sky blue',
	'dim gray',
	'dodger blue',
	'firebrick',
	'floral white',
	'forest green',
	'fuchsia',
	'gainsboro',
	'ghost white',
	'gold',
	'goldenrod',
	'gray',
	'green',
	'green yellow',
	'honeydew',
	'hot pink',
	'indian red',
	'indigo',
	'ivory',
	'khaki',
	'lavender',
	'lavender blush',
	'lawn green',
	'lemon chiffon',
	'light black',
	'light blue',
	'light brown',
	'light buff',
	'light coral',
	'light cyan',
	'light gold',
	'light goldenrod',
	'light gray',
	'light green',
	'light ivory',
	'light magenta',
	'light mustard',
	'light orange',
	'light pink',
	'light red',
	'light salmon',
	'light sea green',
	'light silver',
	'light sky blue',
	'light slate gray',
	'light steel blue',
	'light turquoise',
	'light violet',
	'light yellow',
	'lime',
	'lime green',
	'linen',
	'magenta',
	'maroon',
	'medium aquamarine',
	'medium blue',
	'medium orchid',
	'medium purple',
	'medium sea green',
	'medium slate blue',
	'medium spring green',
	'medium turquoise',
	'medium violet red',
	'midnight blue',
	'mint cream',
	'misty rose',
	'moccasin',
	'mustard',
	'navajo white',
	'navy blue',
	'old lace',
	'olive',
	'olive drab',
	'orange',
	'orange red',
	'orchid',
	'pale goldenrod',
	'pale green',
	'pale turquoise',
	'pale violet red',
	'papaya whip',
	'peach puff',
	'peru',
	'pink',
	'plum',
	'powder blue',
	'purple',
	'rebecca purple',
	'red',
	'rosy brown',
	'royal blue',
	'saddle brown',
	'salmon',
	'sandy brown',
	'sea green',
	'seashell',
	'sienna',
	'silver',
	'sky blue',
	'slate blue',
	'slate gray',
	'snow',
	'spring green',
	'steel blue',
	'tan',
	'teal',
	'thistle',
	'tomato',
	'turquoise',
	'violet',
	'web gray',
	'web green',
	'web maroon',
	'web purple',
	'wheat',
	'white',
	'white smoke',
	'yellow',
	'yellow green'
]
