export const vegetables = [
	'ahipa',
	'amaranth',
	'american groundnut',
	'aonori',
	'arame',
	'arracacha',
	'artichoke',
	'arugula',
	'asparagus',
	'aubergine',
	'avocado',
	'azuki bean',
	'badderlocks',
	'bamboo shoot',
	'beet',
	'beetroot',
	'bell pepper',
	'bitter gourd',
	'bitter melon',
	'black-eyed pea',
	'bok choy',
	'borage',
	'brinjal',
	'broadleaf arrowhead',
	'broccoli',
	'broccolini',
	'brussels sprouts',
	'burdock',
	'cabbage',
	'camas',
	'canna',
	'caper',
	'cardoon',
	'carola',
	'carrot',
	'cassava',
	'catsear',
	'cauliflower',
	'celeriac',
	'celery',
	'celtuce',
	'chaya',
	'chayote',
	'chickpea',
	'chickweed',
	'chicory',
	'chinese artichoke',
	'chinese mallow',
	'chives',
	'collard greens',
	'common bean',
	'common purslane',
	'corn salad',
	'courgette',
	'courgette flowers',
	'cress',
	'cucumber',
	'dabberlocks',
	'daikon',
	'dandelion',
	'daylily',
	'dill',
	'dillisk',
	'dolichos bean',
	'drumstick',
	'dulse',
	'earthnut pea',
	'eggplant',
	'elephant foot yam',
	'elephant garlic',
	'endive',
	'ensete',
	'fat hen',
	'fava bean',
	'fiddlehead',
	'florence fennel',
	'fluted pumpkin',
	'galangal',
	'garbanzo',
	'garden rocket',
	'garland chrysanthemum',
	'garlic',
	'garlic chives',
	'ginger',
	'golden samphire',
	'good king henry',
	'grape',
	'greater plantain',
	'green bean',
	'guar',
	'hamburg parsley',
	'horse gram',
	'horseradish',
	'indian pea',
	'ivy gourd',
	'jerusalem artichoke',
	'jícama',
	'kai-lan',
	'kale',
	'kohlrabi',
	'komatsuna',
	'kuka',
	'kurrat',
	'lagos bologi',
	'lamb lettuce',
	'lamb quarters',
	'land cress',
	'laver',
	'leek',
	'lemongrass',
	'lentil',
	'lettuce',
	'lima bean',
	'lizard tail',
	'loroco',
	'lotus root',
	'luffa',
	'malabar spinach',
	'mallow',
	'manchurian wild rice',
	'marrow',
	'mashua',
	'melokhia',
	'miner lettuce',
	'mizuna greens',
	'moth bean',
	'mung bean',
	'mustard',
	'napa cabbage',
	'new zealand spinach',
	'nopal',
	'okra',
	'olive fruit',
	'onion',
	'orache',
	'pak choy',
	'paracress',
	'parsnip',
	'pea',
	'peanut',
	'pearl onion',
	'pigeon pea',
	'pignut',
	'poke',
	'potato',
	'potato onion',
	'prairie turnip',
	'prussian asparagus',
	'pumpkin',
	'radicchio',
	'radish',
	'rapini',
	'ricebean',
	'runner bean',
	'rutabaga',
	'salsify',
	'samphire',
	'scallion',
	'scorzonera',
	'sculpit',
	'sea beet',
	'sea grape',
	'sea kale',
	'sea lettuce',
	'shallot',
	'shepherd purse',
	'sierra leone bologi',
	'skirret',
	'snap pea',
	'snow pea',
	'soko',
	'sorrel',
	'sour cabbage',
	'soybean',
	'spinach',
	'spring onion',
	'squash',
	'squash blossoms',
	'stridolo',
	'summer purslane',
	'swede',
	'sweet pepper',
	'sweet potato',
	'swiss chard',
	'taro',
	'tarwi',
	'tatsoi',
	'tepary bean',
	'ti',
	'tigernut',
	'tinda',
	'tomatillo',
	'tomato',
	'tree onion',
	'turmeric',
	'turnip',
	'ulluco',
	'urad bean',
	'vanilla',
	'velvet bean',
	'wasabi',
	'water caltrop',
	'water chestnut',
	'water melon',
	'water spinach',
	'watercress',
	'welsh onion',
	'west indian gherkin',
	'wheatgrass',
	'wild leek',
	'winged bean',
	'winter melon',
	'yacón',
	'yam',
	'yao choy',
	'yardlong bean',
	'yarrow',
	'zucchini'
]
